# Cloud Build pipeline for building and deploying to Cloud Run.
#
# Usage (example):
# gcloud builds submit --config cloudbuild.yml \
#   --substitutions=_SERVICE_NAME=classic-touch-painting-site,_REGION=us-central1,_REPOSITORY=cloud-run-images

substitutions:
  _SERVICE_NAME: classic-touch-painting-site
  _REGION: us-west1
  _REPOSITORY: cloud-run-images
  _SMTP_PASS: ""
  _SMTP_USER: ""
  _STAGING_ENABLED: "true"
  _STAGING_PASSWORD: "reymon"
  _STAGING_SESSION_SECRET: ""

steps:
  - name: gcr.io/cloud-builders/docker
    id: Build image
    args:
      - build
      - --set-env-vars
      - SMTP_USER=${_SMTP_USER},SMTP_PASSWORD=${_SMTP_PASSWORD},STAGING_ENABLED=${_STAGING_ENABLED},STAGING_PASSWORD=${_STAGING_PASSWORD},STAGING_SESSION_SECRET=${_STAGING_SESSION_SECRET}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    id: Push image
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy to Cloud Run
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --set-env-vars
      - SMTP_USER=${_SMTP_USER},SMTP_PASSWORD=${_SMTP_PASSWORD},STAGING_ENABLED=${_STAGING_ENABLED},STAGING_PASSWORD=${_STAGING_PASSWORD},STAGING_SESSION_SECRET=${_STAGING_SESSION_SECRET}
      - --allow-unauthenticated

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
