FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

ENV NODE_ENV=production
ENV PORT=3000


ENV SMTP_USER=$_SMTP_USER
ENV SMTP_PASS=$_SMTP_PASS
ENV STAGING_ENABLED=true
ENV STAGING_PASSWORD=$_STAGING_PASSWORD
ENV STAGING_SESSION_SECRET=$_STAGING_SESSION_SECRET

EXPOSE 3000

CMD ["npm", "start"]
