FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

ENV NODE_ENV=production
ENV PORT=3000


ENV SMTP_USER=$SMTP_USER
ENV SMTP_PASS=$SMTP_PASS
ENV STAGING_ENABLED=$STAGING_ENABLED
ENV STAGING_PASSWORD=$STAGING_PASSWORD
ENV STAGING_SESSION_SECRET=$STAGING_SESSION_SECRET

EXPOSE 3000

CMD ["npm", "start"]
